---
driver:
  name: vagrant
  # Custom Vagrantfile for issue #389
  # https://github.com/test-kitchen/kitchen-vagrant/pull/389
  vagrantfile_erb: Vagrantfile.erb
  network:
    - ["private_network", { ip: 192.168.33.6 }]
  customize:
    cpus: 6
    memory: 24576
    cableconnected1: 'on'
    createhd:
      - filename: tmp/storage.vmdk
        size: 16384
    storageattach:
      - storagectl: SATA Controller
        port: 1
        device: 0
        type: hdd
        medium: tmp/storage.vmdk
provisioner:
  name: chef_zero
  always_update_cookbooks: true
  nodes_path: test/fixtures/nodes
  clients_path: test/fixtures/clients
  environments_path: test/fixtures/environments
  data_bags_path: test/fixtures/data_bags
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[edmonton::default]
      - recipe[edmonton::postgresql]
      - recipe[edmonton::shapefiles]
      - recipe[edmonton::geoserver]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      chef_vault:
        databags_fallback: true
