---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
    cableconnected1: 'on'

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  nodes_path: test/fixtures/nodes
  clients_path: test/fixtures/clients
  environments_path: test/fixtures/environments
  data_bags_path: test/fixtures/data_bags
  client_rb:
    environment: test
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    driver:
      network:
        - ["private_network", { ip: "192.168.33.55" }]
    run_list:
      - recipe[gsw-frost-server::default]
      - recipe[asw-etl::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      airflow:
        executor: SequentialExecutor
      sensorthings:
        external_uri: "http://localhost:8080/FROST-Server/v1.0/"
      chef_vault:
        databags_fallback: true
