---
driver:
  name: vagrant
  customize:
    cableconnected1: 'on'
  network:
    - ["private_network", { ip: "192.168.33.8" }]

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[stoney::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
