---
driver:
  name: vagrant
  customize:
    cableconnected1: 'on'
    memory: 9182
    cpus: 6
  network:
    - ["private_network", { ip: "192.168.33.90" }]

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  data_bags_path: "test/data_bags"
  encrypted_data_bag_secret_key_path: "test/encrypted_data_bag_secret"
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[sarcee::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      apt:
        http_proxies:
          - "http://192.168.1.50:3142"
        https_proxies:
          - "DIRECT"
      sarcee:
        # set this to the part of the disk by-id that shows up in
        # virtualbox for you
        docker_volume_id: "VB526829ce-69998b9b"
        user: vagrant
      dokku:
        keyfile: "/home/vagrant/.ssh/id_rsa.pub"
