---
driver:
  name: vagrant
  customize:
    cableconnected1: 'on'

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[beddington::default]
    attributes:
