---
driver:
  name: vagrant
  customize:
    cableconnected1: 'on'
    memory: 512
    cpus: 1
    
    createhd:
      - filename: beddington.vmdk
        size: 10240
        format: vmdk
    storageattach:
      - storagectl: SATA Controller
        port: 1
        device: 0
        type: hdd
        medium: beddington.vmdk

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04

suites:
  - name: default
    run_list:
      - recipe[beddington::default]
    attributes:
