source 'https://rubygems.org'

ruby '2.7.0'

gem 'berkshelf'
gem 'chef'
gem 'cookstyle'
gem 'foodcritic'
gem 'kitchen-inspec'
# This fork is necessary to use for creating additional HDs for local
# testing. Can be replaced with the primary version when this PR is
# merged: https://github.com/test-kitchen/kitchen-vagrant/pull/389
gem 'kitchen-vagrant',
  git: "https://github.com/Ecodev/kitchen-vagrant",
  branch: "createhd_existing"
gem 'test-kitchen'
