default["openjdk"]["version"] = "11.0.2"
default["openjdk"]["prefix"] = "/opt/java"
default["openjdk"]["download_url"] = "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz"
default["openjdk"]["checksum_url"] = "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz.sha256"
default["openjdk"]["checksum_type"] = "SHA256"
