default["openjdk"]["version"] = "11.0.2"
default["openjdk"]["prefix"] = "/opt/java"
default["openjdk"]["download_url"] = "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz"
default["openjdk"]["checksum_url"] = "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz.sha256"
default["openjdk"]["checksum_type"] = "SHA256"

default["tomcat"]["version"] = "9.0.19"
default["tomcat"]["prefix"] = "/opt/tomcat"
default["tomcat"]["download_url"] = "http://muug.ca/mirror/apache-dist/tomcat/tomcat-9/v9.0.19/bin/apache-tomcat-9.0.19.tar.gz"
default["tomcat"]["checksum_url"] = "https://www.apache.org/dist/tomcat/tomcat-9/v9.0.19/bin/apache-tomcat-9.0.19.tar.gz.sha512"
default["tomcat"]["checksum_type"] = "SHA512"
