default["openjdk"]["version"] = "11.0.2"
default["openjdk"]["prefix"] = "/opt/java"
default["openjdk"]["download_url"] = "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz"
default["openjdk"]["checksum_url"] = "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz.sha256"
default["openjdk"]["checksum_type"] = "SHA256"

default["tomcat"]["version"] = "9.0.19"
default["tomcat"]["prefix"] = "/opt/tomcat"
default["tomcat"]["download_url"] = "http://muug.ca/mirror/apache-dist/tomcat/tomcat-9/v9.0.19/bin/apache-tomcat-9.0.19.tar.gz"
default["tomcat"]["checksum_url"] = "https://www.apache.org/dist/tomcat/tomcat-9/v9.0.19/bin/apache-tomcat-9.0.19.tar.gz.sha512"
default["tomcat"]["checksum_type"] = "SHA512"

default["gdal"]["version"] = "2.4.1"
default["gdal"]["prefix"] = "/opt/gdal"
default["gdal"]["download_url"] = "http://download.osgeo.org/gdal/2.4.1/gdal-2.4.1.tar.gz"
default["gdal"]["checksum_url"] = "http://download.osgeo.org/gdal/2.4.1/gdal-2.4.1.tar.gz.md5"
default["gdal"]["checksum_type"] = "MD5"

default["geoserver"]["version"] = "2.15.1"
default["geoserver"]["prefix"] = "/opt/geoserver"
default["geoserver"]["download_url"] = "http://sourceforge.net/projects/geoserver/files/GeoServer/2.15.1/geoserver-2.15.1-war.zip"
