source 'https://supermarket.chef.io'

metadata

# List Private Cookbooks (not from Chef supermarket) here
cookbook "chef-server-with-letsencrypt", git: "https://gitlab.com/virtkick/chef-server-with-letsencrypt.git"
