---
driver:
  name: vagrant
  network:
    - ["private_network", { ip: "192.168.33.15" }]
  customize:
    cpus: 2
    memory: 4096
    cableconnected1: 'on'

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  nodes_path: test/fixtures/nodes
  clients_path: test/fixtures/clients
  environments_path: test/fixtures/environments
  data_bags_path: test/fixtures/data_bags
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[deerfoot::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
