---
driver:
  name: vagrant
  customize:
    cableconnected1: 'on'

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[banff::acme_server]
      - recipe[banff::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      acme:
        dir: https://127.0.0.1:14000/dir
        contact:
          - mailto:admin@example.com
