source 'https://rubygems.org'

ruby '2.5.1'

gem 'berkshelf'
gem 'chef', '~> 14.7.17'
gem 'chef-vault', '~> 3.4.3'
gem 'cookstyle'
gem 'foodcritic'
gem 'kitchen-inspec'
gem 'kitchen-vagrant'
gem 'test-kitchen', '1.23.2'

