---
driver:
  name: vagrant
  customize:
    cableconnected1: 'on'
  network:
    - ["private_network", { ip: "192.168.33.101" }]

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  nodes_path: test/fixtures/nodes
  clients_path: test/fixtures/clients
  environments_path: test/fixtures/environments
  data_bags_path: test/fixtures/data_bags
  client_rb:
    chef_license: accept
    environment: test

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[shaganappi::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      chef_vault:
        databags_fallback: true
