---
driver:
  name: vagrant
  network:
    - ["private_network", { ip: "192.168.33.65" }]
  customize:
    cpus: 2
    memory: 2048
    cableconnected1: 'on'

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  nodes_path: test/fixtures/nodes
  clients_path: test/fixtures/clients
  environments_path: test/fixtures/environments
  data_bags_path: test/fixtures/data_bags
  client_rb:
    environment: test
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[blackfoot::frost]
      - recipe[blackfoot::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      sensorthings:
        external_uri: "http://192.168.33.65:8080/FROST-Server/v1.0/"
      frost:
        service_root_url: "http://192.168.33.65:8080/FROST-Server"
      chef_vault:
        databags_fallback: true
